apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ginflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: backend
        image: registry.gin-telecom.ovh/ginflix/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: ginflix-config
              key: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: ginflix-config
              key: KEYCLOAK_REALM
        - name: KEYCLOAK_HOST
          valueFrom:
            configMapKeyRef:
              name: ginflix-config
              key: KEYCLOAK_HOST
        - name: GARAGE_ENDPOINT
          value: "s3.gin-telecom.ovh"
        - name: GARAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: bucket
        - name: GARAGE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key
        - name: GARAGE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-key
        - name: S3_ENDPOINT
          value: "https://s3.gin-telecom.ovh"
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: bucket
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-key
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_S3_ENDPOINT
          value: "https://s3.gin-telecom.ovh"
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: ginflix-config
              key: MONGO_URI
---
# Service Backend
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ginflix
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend