apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer
  namespace: ginflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamer
  template:
    metadata:
      labels:
        app: streamer
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: streamer
        image: registry.gin-telecom.ovh/ginflix/streamer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: GARAGE_ENDPOINT
          value: "s3.gin-telecom.ovh"
        - name: GARAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: bucket
        - name: GARAGE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key
        - name: GARAGE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-key
        - name: S3_ENDPOINT
          value: "https://s3.gin-telecom.ovh"
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: bucket
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-key
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_S3_ENDPOINT
          value: "https://s3.gin-telecom.ovh"
---
apiVersion: v1
kind: Service
metadata:
  name: streamer-service
  namespace: ginflix
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: streamer